#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    position=bottom \
    padding_left=10 \
    padding_right=5

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

## Add space item
sketchybar --add event aerospace_workspace_change
sketchybar --add item current_space left
sketchybar --subscribe current_space aerospace_workspace_change

sketchybar --set current_space \
  script="$PLUGIN_DIR/current_space.sh" \


## Add front app item
sketchybar --add item front_app left

# Subscribe to the front_app_switched event
sketchybar --subscribe front_app front_app_switched

# Customize the front_app
sketchybar --set front_app \
  script="$PLUGIN_DIR/front_app.sh"

## Add Clock item
sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
